services:
  openvoice:
    build:
      context: openvoice
      dockerfile: Dockerfile
    ports:
      - 8877:8877
      - 8888:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
