services:
  openvoice:
    build:
      context: openvoice
      dockerfile: Dockerfile
    volumes:
      - huggingface:/root/.cache/huggingface/hub
      - nltk_data:/root/nltk_data
      - ./openvoice-repo:/app/openvoice-repo
    ports:
      - "8888:8888" # for jupyter
      - "8080:8080" # for fastapi
    command: ["/root/.pyenv/versions/3.9.19/bin/uvicorn", "fast:app", "--port=8080", "--host=0.0.0.0", "--reload"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  gradio:
    build:
      context: gradio-app
      dockerfile: Dockerfile
    ports:
      - "7860:7860" # for gradio
    command: ["/root/.pyenv/versions/3.9.19/bin/gradio", "app.py"]

volumes:
  huggingface:
  nltk_data:
