services:
  openvoice:
    build:
      context: openvoice
      dockerfile: Dockerfile
    volumes:
      - huggingface:/root/.cache/huggingface/hub
      - nltk_data:/root/nltk_data
      - ./openvoice-repo:/app/openvoice-repo
    ports:
      - "8888:8888" # for jupyter
      - "7860:7860" # for gradio
      - "8080:8080" # for fastapi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  huggingface:
  nltk_data:
    # name: repo
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: /mnt/c/openvoice-docker/openvoice-repo
